### ISSUE TITLE
script.crossOrigin = "anonymous";

### ISSUE THREAD

**Issue by mi4tin** [MriLiuJY/monitorFE#36]
这个是否有兼容 问题

**Comment by MriLiuJY** [comment]
"crossorigin" 支持在IE 10以上，且在使用的时候会强制要求服务端设置响应头 `Access-Control-Allow-Origin`, 

且 "crossorigin" 的属性会将一个简单请求变成复杂请求，及会像 `POST`请求一样先发出 `OPTION` 请求探测是否设置 `Access-Control-Allow-Origin` 允许跨域。

**Comment by MriLiuJY** [comment]
> 这个是否有兼容 问题

"crossorigin" 支持在IE 10以上，且在使用的时候会强制要求服务端设置响应头 Access-Control-Allow-Origin,

且 "crossorigin" 的属性会将一个简单请求变成复杂请求，及会像 POST请求一样先发出 OPTION 请求探测是否设置 Access-Control-Allow-Origin 允许跨域。
